### PR TITLE
Add configurable timeout to config, httpbase and all http requests

### PR DESCRIPTION
**Pull request by ZxMYS**
Hi! 
~This is not a complete PR - tests have not been done yet - but I'd like to check first whether this change is reasonable with you.~ update: this is a complete PR now.

I found that the call to requests.request in httpbase doesn't have a timeout set, which means if the server is not responsive  and doesn't drop connection the request call will wait infinitely (since the default timeout of requests is no timeout), which can make the calling thread stuck. So here I'd like to add a config parameter to make the timeout configurable. Do you think this is a reasonable change (and it is correct to do the change in this way?)? I'm completely new to this codebase so might be terribly wrong.

Thanks!

### All Submissions:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you added an explanation of what problem you are trying to solve with this PR?
* [x] Have you added information on what your changes do and why you chose this as your solution?
* [x] Have you written new tests for your changes?
* [x] Does your submission pass tests?
* [x] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by c00kiemon5ter** [comment]
Hello again and thanks!

two points:
1. the option is now named `timeout` which is super generic; I would probably rename it to something like `http_client_timeout`.

2. this now covers all calls that use HTTPBase, but other calls (which unfortunately are not using the same code path) are not receiving any timeout. An example is usage of the `requests` library to do network calls, and specifically the `MetaDataMDX` class that invokes the `_fetch_metadata` method.
  Do you think that those calls could be covered too?

Let me know if you want to have a go on this, or if I should get into it later.

**Comment by ZxMYS** [comment]
Sure, I will update later.

**Comment by ZxMYS** [comment]
Ok, I think now I have covered all requests calls. (I greped 'requests.' in the src folder) 
PTAL :)

**Comment by ZxMYS** [comment]
@c00kiemon5ter Hi, have you reviewed the updated code? I see the new tag but not sure if that means this has been reviewed :)

**Comment by c00kiemon5ter** [comment]
a Github bug? I don't know why this was closed but it also cannot be re-opened..
I will merge this locally.

**Comment by c00kiemon5ter** [comment]
merged by [d23562b](https://github.com/IdentityPython/pysaml2/commit/d23562b26ff328ef2ecfa519edb786a7b2404911)

**Comment by peppelinux** [comment]
in oidc we use httpc_params that is a dict object containing all the params supported by python requests

@ivan would we like to adopt this approach?

**Comment by ivan** [comment]
Please don't @ the wrong ivan, github sends me emails

**Pull request closed without merging**
