### PR TITLE
Use cryptography.x509 for certificate loading

### LINKED ISSUE #659: x509 certificate with trailing whitespace doesn't load
When reading x509 certificates in order to produce metadata, the library assumes that the first and last lines are the begin/end certificate markers, and blindly trims them:
https://github.com/IdentityPython/pysaml2/blob/v5.0.0/src/saml2/metadata.py#L832

If you have a cert with a trailing blank line this result in the metadata being generated an invalid certificate.

The `cyptography` library itself handles leading/trailing data without issue.

## Code Version
Latest

## Expected Behavior
The library should not produce invalid metadata when presented with a PEM certificate with a trailing new line.

## Current Behavior
Invalid metadata

## Possible Solution
Load the given PEM data and serialize it back out using the cryptography library. This would also catch any other issues with the certificate data:

```
cert = x509.load_pem_x509_certificate(pem_data, default_backend())
pem_data = cert.public_bytes(serialization.Encoding.PEM)[1:-1]
```

### PR DESCRIPTION
**Pull request by ioparaskev**
- Uses cryptography.x509 load_pem_x509_certificate or
  load_der_x509_certificate depending on the cert type. This ensures 1)
the certificate is a valid certificate 2) trailing newlines and
whitespaces will be ignored
- Adds tests for the above scenarios
- Ignores cer/crt as certificate type since these are file extensions
  and do not guarrantee the certificate encoding. Uses "pem" as default
type (mostly for backward compatibility). Only other valid option is
"der" (everything else falls back to "pem")
- Uses sigver cert loading function for the metadata cert loading
  (removes read_cert function)
- Fixes #659

### All Submissions:

* [X] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [X] Have you added an explanation of what problem you are trying to solve with this PR?
* [X] Have you added information on what your changes do and why you chose this as your solution?
* [X] Have you written new tests for your changes?
* [X] Does your submission pass tests?
* [X] This project follows PEP8 style guide. Have you run your code against the 'flake8' linter?

### CODE REVIEW

**Comment by peppelinux** [comment]
Is there any possibilità to handle also https://github.com/IdentityPython/pysaml2/issues/278 in this PR?

**Comment by c00kiemon5ter** [comment]
I don't think we should handle #278 here. I also don't certificate-passwords are widely used. Let's keep this issue about loading certificates only and we can revisit certificate-passwords again in the future in a different issue/PR.

**Comment by peppelinux** [comment]
I marked that as closing and then closed It, now I've reopened it again. I have a presentiment that It would be a "won't fix" but my excuse in Advance, I didn't mean to be cynical

**Comment by peppelinux** [comment]
I puished this feature here
https://github.com/IdentityPython/pysaml2/pull/754/commits/daf2142b6fdb2a0bed7da585d7717fdfdd47293e#diff-3482e02155ca5e77a0034bd27c342d3951400f11ceea80ed7d2169e8f458f857R105

Probably it would belong to this PR.
Don't know which PR would be merged first, so, let me know your though, eventually I can push it also in this PR

**Comment by c00kiemon5ter** [comment]
closed by a9244357

**Pull request closed without merging**
